### ISSUE TITLE
Link to documentation broken

### ISSUE THREAD

**Issue by HTownsendis** [NMFS-ecosystem-tools/VES-V#3]
Clicking the documentation button, opens a new tab in the browser with this url: https://nmfs-ecosystem-tools.github.io/VES-V/VES-V%20User%20Manual_v137_final.pdf

The page itself gives a 404 error, but the v137 manual is in the repository.

**Comment by CorinneBassin-NOAA** [comment]
fixed, might take 30 minutes for the server to refresh but works on an incognito page currently
